const PaperNames = [
	"Butterfly Paper",
	"Airmail Paper",
	"New Year's Cards",
	"Lacy Paper",
	"Cloudy Paper",
	"Petal Paper",
	"Snowy Paper",
	"Maple-leaf Paper",
	"Lined Paper",
	"Notebook Paper",
	"Flowery Paper",
	"Polka-dot Paper",
	"Bottle Paper",
	"Ribbon Paper",
	"Sparkly Paper",
	"Vine Paper",
	"Formal Paper",
	"Snowman Paper",
	"Card Paper",
	"Leopard Paper",
	"Cow Paper",
	"Camouflage Paper",
	"Hamburger Paper",
	"Piano Paper",
	"Nook Paper",
	"Fox Paper",
	"Birthday Cards",
	"Four-leaf Paper",
	"Town-hall Paper",
	"Tortimer Paper",
	"Insurance Paper",
	"Academy Paper",
	"Lovely Paper",
	"Rainbow Paper",
	"Egyptian Paper",
	"Lotus Paper",
	"Tile Paper",
	"Mosaic Paper",
	"Elegant Paper",
	"Town View Paper",
	"Chinese Paper",
	"Ocean Paper",
	"Industrial Paper",
	"Fireworks Paper",
	"Floral Paper",
	"Mushroom Paper",
	"Star Paper",
	"Composer Paper",
	"Bathtub Paper",
	"SMB3 Paper",
	"Cool Paper",
	"Forest Paper",
	"Bubble Paper",
	"Buttercup Paper",
	"Tartan Paper",
	"Plaid Paper",
	"Lemon-lime Paper",
	"Crater Paper",
	"Bejeweled Paper",
	"Geometric Paper",
	"Southwest Paper",
	"Night Sky Paper",
	"Chic Paper",
	"Goldfish Paper"
];

export default PaperNames;